all: ${DBG_ROOT}/graph-convert-utils/convert.cpp
	g++ -o ${DBG_ROOT}/graph-convert-utils/convert -fopenmp ${DBG_ROOT}/graph-convert-utils/convert.cpp

clean:
	rm -rf ${DBG_ROOT}/graph-convert-utils/convert ${DBG_ROOT}/graph-convert-utils/*.o
